coala/projects

data/projects.js
data/projects/jetbrains-ide-plugin.md

New project: coala plugin for jetbrains IDEs
https://github.com/coala/coala/issues/2019
```text
Ce Gao @gaocegege 17:56
Hi, could we add coala/coala#2019 to projects.coala.io? There are many people use jetbrains IDEs.  It makes sense.
Lasse Schuirmann @sils 17:57
yeah certainly, we'd also have a comentor from jetbrains, can you make a project? I'll contact him
Ce Gao @gaocegege 17:58
Of course
Lasse Schuirmann @sils 17:59
contacted jetbrains, check. We might well get a comentor from them
```
Signed-off-by: Ce Gao <ce.gao@outlook.com>

projects: Add jetbrains ide plugin project

---

partials/tabs/projects.html

This is done so that divs do not
overlap and issue chips are clickable
Fixes https://github.com/coala/projects/issues/172

projects.html: Add space below issues

---

resources/js/app.js

This ensures that projects navigate only on pressing left/right arrow key.
Fixes:https://github.com/coala/projects/issues/171

app.js: Fix arrow key navigation issue

---

data/projects/debug_profile.md

Under milestones -> participation/bonding -> The applicant is has gone through the pdb docuemntation.
Removed  "is"
closes #211
- [ x] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [ x] I ran coala over my code locally. (*All commits have to pass

debug_profile.md: corrected grammar removed "is"

---

index.html

On clicking the projects or mentors or FAQ tab
while holding the CTRL button, the page must
appear in a new tab on the browser.
Fixes https://github.com/coala/projects/issues/229
them.
After you submit your pull request, **DO NOT …

index.html: Open a new tab

---

partials/tabs/projects.html

causing link behind it unclickable.
Fixes https://github.com/coala/projects/issues/273

Fix overlaping invisible block element

---

_projects/add_repo_license.md

This task is a basic outline for licensing linting.

New GCI repeatable task: Add repo license

---

_projects/antlr_v4.md
_projects/aspects.md
_projects/bear_updates.md
_projects/coala_web.md
_projects/cobot_enhancement.md
_projects/commit_based_perftest.md
_projects/communication_bridge.md
_projects/debug_profile.md
_projects/documentation_extraction.md
_projects/editor_support.md
_projects/enhance_coala_quickstart.md
_projects/extend_linter_integration.md
_projects/generic_bears.md
_projects/gitmate_gitlab.md
_projects/implement_aspects.md
_projects/implement_metrics_for_coala.md
_projects/improve_diff_handling.md
_projects/integrate-pyflakes-AST.md
_projects/jetbrains-ide-plugin.md
_projects/nested_languages.md
_projects/newcomer_metrics.md
_projects/optimize_caching.md
_projects/pr_perftest.md
_projects/roberta_external_source.md
_projects/rstcheck_with_better_sphinx_support.md
_projects/use_coala.md
_projects/use_coala_2.md
_projects/use_coala_3.md
_projects/vulture.md

GitBook does not understand YAML document start markers
that have trailing whitespace.
Fixes https://github.com/coala/projects/issues/386

_projects: Fix trailing whitespace in YAML markers

---

.coafile
.travis.yml
reports/satwikkansal.md

Closes https://github.com/coala/projects/issues/13

Re-activate coala-ci

---

partials/tabs/mentors.html

Makes the whole mentor and admin card a clickable link to their github profiles so that user knows that it is clickable.
Fixes https://github.com/coala/projects/issues/69
them.
After you submit your pull request, **DO NOT click the …

mentors.html: Mentor card made clickable

---

_faq/application_template.md

Link changed from https://github.com/coala/projects/blob/master/data/projects.js to
https://github.com/coala/projects/blob/master/data/projects.liquid.
Fixes https://github.com/coala/projects/issues/442

FAQ: Fix broken link

---

resources/js/app.js

Closes https://github.com/coala/projects/issues/491
them.
instead.
Please …

app.js: Exclude mentors on completed projects

---

_config.yml
index.html
resources/css/style.css

Adds a Github fork ribbon and a button responsively, uses https://blog.github.com/2008-12-19-github-ribbons/ and https://buttons.github.io/.
Closes https://github.com/coala/projects/issues/511.

Adds github fork ribbons and buttons

---

_faq/own_project_idea.md
_faq/thesis.md

These changes replace links to data/projects.js with links to the projects repository. The wording of the links has also been changed from 'project list' --> 'project repository'.
Fixes https://github.com/coala/projects/issues/395
them.

faq: Replace dead links to projects.js

---

_projects/convert_bear_to_aspects.md

The `aspects` project is the uncompleted project to convert bear to aspect, and `implement aspects` is already completed in GSOC 2017.
cc @jayvdb

Update aspects project description

---

_projects/git_task_list.md

Related to:
https://github.com/coala/projects/issues/480
https://github.com/coala/coala/issues/4080
them. …

git_task_list.md: Add Git Task List project

---

reports/example.md

Following changes have been made to the GSoC report template:
Closes: #615

reports/example.md: Update GSoC report template

---

_config.yml
_reports/AlexMaxim.md
_reports/HemangKumar.md
_reports/MeetMangukiya.md
_reports/NaveenKumarSangi.md
_reports/RahulJha.md
_reports/adhikasp.md
_reports/example.md
_reports/li-boxuan.md
_reports/pareksha.md
_reports/satwikkansal.md

This provides automatic permalinks matching
those used in 2017.  The file name is used
as the final component.
The added categories are not used, as jekyll
converts them to lower-case which breaks existing
URLs.
Related to https://github.com/coala/projects/issues/359

Create reports collection

---

.coafile

Ignore _reports directory from
`filenames` section.

.coafile: Ignore _reports dir

---

_projects/antlr_v4.md
_projects/git_task_list.md
data/projects.liquid
partials/tabs/projects.html

Add support for multiple status labels on a project card
Closes https://github.com/coala/projects/issues/470
them. …

Flags: Support for multiple status labels

---

_reports/kriti21.md

https://deploy-preview-612--coala-projects.netlify.com/gsoc/2018/statusreport/kriti21

reports: Add Kriti Rohilla'a GSoC report

---

_reports/saksham.md

https://deploy-preview-630--coala-projects.netlify.com/gsoc/2018/statusreport/saksham

reports: Add anctartica's GSoC report

---

_reports/macbox7.md

https://deploy-preview-614--coala-projects.netlify.com/gsoc/2018/statusreport/macbox7

report: Add macbox7 GSoC report

---

_reports/example.md

Jekyll uses the year to create the page URL
Related to https://github.com/coala/projects/issues/359
them. …

_reports/example.md: Add date

---

_projects/integrate-pyflakes-AST.md
resources/js/app.js

This redirects the user from link
http://projects.coala.io/#/projects?project=integrate_pyflakes-enhanced_ast_into_coala_
to http://projects.coala.io/#/projects?project=integrate_pyflakes-enhanced_ast_into_coala
Fixes https://github.com/coala/projects/issues/573
them.
likely receive a lot of bot comments and build failures if coala …

Remove trailing space from pyflakes project

---

_config.yml
_faq/application-template.md

Have the year on the GSoC application template on the FAQ page change based on the month. If it's past September, the page will show the next year, otherwise it will show the current year.
Closes https://github.com/coala/projects/issues/671

application-template.md: Make GSoC application template dynamic

---

partials/tabs/projects.html

The following commit adds a link of past years **GSoC project reports** in projects.html, just below the project ideas [link](https://projects.coala.io/#/projects) under the search bar.
Fixes https://github.com/coala/projects/issues/683
them.
pass on every …

projects.html: Added GSoC project reports link

---

_layouts/report.md
_reports/AlexMaxim.md
_reports/HemangKumar.md
_reports/MeetMangukiya.md
_reports/NaveenKumarSangi.md
_reports/RahulJha.md
_reports/adhikasp.md
_reports/macbox7.md
_reports/satwikkansal.md
resources/css/style.css

As per issue, I have added the computed sha256sum hash values for
patch tarball for all the 2017 report files and display them on the
project report webpage.
Closes https://github.com/coala/projects/issues/627
them.
After you …

reports: Display sha256sum on webpage

---

_projects/bear-updates.md
_projects/documentation-extraction.md
_projects/nested-languages.md

As I won't be available as a mentor for coala for the
forseeable future, I would like my name removed from
all projects, so people don't contact me about them.

projects: Remove NiklasMM as mentor for all projects

---

README.md

Closes https://github.com/coala/projects/issues/477

README.md: Modify steps of Usage

---

_projects/result-reporter-tool.md

Closes https://github.com/coala/projects/issues/555
them.
instead.
Please …

Add result reporter tool project

---

.coafile
.gitignore
.travis.yml
README.md

.travis.yml: Remove GitHub merge commit workaround

---

_projects/enhance-and-improve-coala-community-and-projects-website.md

This commit adds new Project Proposal - "Enhance
websites architecture" to current projects list.
Closes #691

_projects: Add "Enhance Website Architecture" project to projects list

---

_layouts/report.md
index.html
partials/tabs/projects.html
partials/tabs/students.html
reports.html
resources/css/style.css
resources/js/app.js

The commit replaces the reports web-page by the
students web-page. This displays all the GSoC students
using the same logic as used in reports.html for reading
all the work reports.
Closes #734

students.html: Add a tab displaying GSoC Students 

---

partials/tabs/projects.html
resources/js/app.js

The commit sorts the projectsList itself in the JavaScript file
using `orderBy` filter and set the sorted array globally, which
omits the use of `orderBy` filter in `projects.html` file
Fixes #711

app.js: Sort projects acc. to status in scope

---

partials/tabs/projects.html

The coala projects site https://projects.coala.io/#/projects didn't had
hyperlink to the mentors' name in the modal window of each project
description. This improvement adds hyperlink to it for convenience.
Closes https://github.com/coala/projects/issues/36
them.
likely receive a lot of bot comments and build failures if coala does …

projects.html: Add hyperlink to the mentors' name

---

_projects/git-bug.md

Following https://github.com/coala/projects/issues/648, this PR add git-bug to the list of GSOC projects.

_projects: add git-bug to the list of projects

---

partials/tabs/projects.html

This fixes the close position which was out of the filter box and changes 'Filter Projects' heading tag: h6 to h4
Fixes #785
them.
When asked for a …

projects.html: Fix close sign on filter dialog box

---

resources/js/directives/projects.js

This will fix the randomly redirecting issue of projects URL on refreshing the page of the project or while pasting the link in the search bar, and remove hard-coded redirection of pyFlakes as it is no more required.
Fixes https://github.com/coala/projects/issues/793
them.
likely receive a lot of bot comments and build failures if …

projects.js: Fix randomly redirecting issue
