coala/projects

data/faq.js
partials/tabs/faq.html

faq.html: Add foldable FAQs section

---

data/projects.js
index.html
resources/js/app.js

index.html: Add projects data structure

---

index.html
resources/js/app.js
vendors/materialize/css/materialize.css

Removes mentor reference in app.js
Fixes #11

index.html: Add proper links

---

data/faq.js

faq: Add meaningful questions

---

resources/js/app.js

mentors: Add mentors data structure

---

partials/tabs/projects.html
resources/css/style.css
resources/js/app.js

projects.html: Add popup view for projects

---

data/projects.js

I just tried to distribute projects evenly. We'll need to reallocate
mentors possibly later again.

projects: Remove a few mentors

---

partials/tabs/mentors.html
partials/tabs/projects.html
resources/css/style.css

- Fonts for mentor in main page and search box styling
- Decreasing height in mentors tab

Solves Frontend issues

---

data/faq.js

Added faq regarding start of proposal
Closes:null

faq.js: Add faq

---

index.html
partials/tabs/projects.html
resources/css/style.css

-  Improves styling in card
- Eliminates excessive uppercasing

style.css: Fix style issues

---

data/projects.js

The script splits off the first period to get the short description
apparently so lets make that a nice one.

projects: Improve first sentence

---

README.md
data/projects.js
data/projects/create_jenkins_plugin.md
data/projects/extend_linter_integration.md
data/projects/implement_metrics_for_coala.md
data/projects/improve_diff_handling.md
index.html
partials/tabs/faq.html
partials/tabs/projects.html
resources/css/style.css
resources/js/app.js
vendors/angular-sanitize/angular-sanitize.js
vendors/markdown/markdown.js
vendors/showdown/showdown.js

Closes https://github.com/coala/projects/issues/8
- wrt fee8f34
Eg: The link in 3rd line -  'the linter documentation' is being converted to HTML

index.html: Add support for markdown

---

README.md

These instructions are essential for developers to properly test out the local version of the website.
Fixes https://github.com/coala/projects/issues/75

README.md: Add instructions on how to use projects

---

data/projects/coala_web.md

Change `The blog is has sections` to `The blog has sections`
Fixes https://github.com/coala/projects/issues/85

coala_web.md: Correct grammatical mistake

---

data/faq.js
data/projects.js
data/projects/debug_profile.md
data/projects/extend_linter_integration.md
data/projects/implement_metrics_for_coala.md
data/projects/improve_diff_handling.md
data/projects/nested_languages.md

So students know what they are.

projects: Link cEP

---

index.html
partials/tabs/projects.html
resources/css/style.css

Fixes https://github.com/coala/projects/issues/38
Footer Before
After

index.html: Improve responsiveness

---

partials/tabs/projects.html
resources/css/style.css

Closes https://github.com/coala/projects/issues/94

projects.html: Add markdown to html in requirements

---

data/projects.js
partials/tabs/projects.html
resources/js/app.js

Closes https://github.com/coala/projects/issues/87

projects.js: Add json field for suborg

---

data/projects.js

Change difficulty label of Aspects Support project from hard to high
to follow standard.
Fixes https://github.com/coala/projects/issues/112

projects.js: Change difficulty label

---

data/admins.js
data/faq.js
data/faq/contact_mentor.md
data/faq/gsoc_requirements.md
data/faq/i_want_to_do_a_gsoc.md
data/faq/mentor_obligations.md
data/faq/own_project_idea.md
data/faq/student_obligations.md
data/faq/working_out_the_proposal.md
data/faq/writing_a_great_proposal.md
index.html
partials/tabs/faq.html
partials/tabs/mentors.html
partials/tabs/projects.html
resources/css/style.css
resources/js/app.js

Improves List item alignment
Adds initiatives and suborg in overview
Admins (Description message needs polishing)
FAQ Markdown

 milestone: Need for submission

---

data/projects.js
data/projects/rstcheck_with_better_sphinx_support.md

This is as discussed over email with @sils.

Add an rstcheck project

---

data/projects/improve_installation.md

projects: Add improve_installation.md

---

index.html

The title of the website was changed 
from 'coala' to 'coala Projects' 
because it sounds better
Fixes https://github.com/coala/projects/issues/68

index.html: Change title of website

---

resources/css/style.css

Change display from block to inline-block
of span elements inside cards
Fixes https://github.com/coala/projects/issues/131

style.css: Change display to inline-block

---

data/projects.js

He agreed via mail to help out.

projects: Add uhafner as jenkins comentor

---

data/projects/improve_installation.md

Check and fix all the grammatical mistakes.

improve_installation.md: Fix grammatical mistakes

---

partials/tabs/projects.html
resources/css/style.css
resources/js/app.js

Markdown rendering correctly in Project Description
Fixes #144

app.js: Remove unused filter filter_desc

---

index.html
partials/tabs/projects.html
resources/css/style.css
resources/js/app.js

Fixes https://github.com/coala/projects/issues/150
Also add arrows for project navigation

app.js: Use encodeURIComponent for project urls

---

resources/js/app.js

Closes: https://github.com/coala/projects/issues/158

app.js: Remove modal animation on transition

---

data/projects.js

Add NiklasMM as metor for update_bears and
nested_languages.

mentors: Add NiklasMM as mentor

---

data/projects/antlr_v4.md
data/projects/aspects.md
data/projects/bear_updates.md
data/projects/coala_cli.md
data/projects/coala_web.md
data/projects/communication_bridge.md
data/projects/create_jenkins_plugin.md
data/projects/debug_profile.md
data/projects/editor_support.md
data/projects/extend_linter_integration.md
data/projects/generic_bears.md
data/projects/gitmate_gitlab.md
data/projects/implement_aspects.md
data/projects/implement_metrics_for_coala.md
data/projects/improve_diff_handling.md
data/projects/improve_installation.md
data/projects/jetbrains-ide-plugin.md
data/projects/nested_languages.md
data/projects/optimize_caching.md
data/projects/rstcheck_with_better_sphinx_support.md

Clarifies the end of community bonding
Closes https://github.com/coala/projects/issues/119

data/projects/*.md: Replace "CODING STARTS" with "COMMUNITY BONDING"

---

partials/tabs/mentors.html
partials/tabs/projects.html

mentors.html:removed center tag
projects.html:removed center tag
Removed both the Tags as they were deprecated
Fixes #44

Removed deprecated center tags

---

README.md

Issue #119 --> https://github.com/coala/projects/issues/119 should have also taken
care of README.md. Now that small change has been made which was over-looked.
Closes https://github.com/coala/projects/issues/168

README.md: Replace "CODING STARTS" by "COMMUNITY BONDING"

---

index.html
partials/tabs/projects.html
resources/css/style.css
vendors/materialize/css/materialize.css

style.css: Add capitalize
Add capitalize which transforms the first letter of each word to uppercase
style.css: Add uppercase
Add uppercase transforms all characters to uppercase
style.css:Add lowercase
Add lowercase transforms all characters to lowercase
Closes #54

Text Transformations.

---

resources/js/app.js

Fixes:https://github.com/coala/projects/issues/160

app.js: Project URLs changing on left/right navigation

---

resources/js/app.js

Fixes https://github.com/coala/projects/issues/175

app.js: Unset current project on modal close

---

data/projects.js

Add myself as a co-mentor to these two projects
- Improve Diff Handling (difficulty Low and it already has 2 other mentors)
- Improve coala website & supporting tools (difficulty medium, and it has 2 other mentors)

Add Mariatta as a co-mentor

---

README.md

Added projects.coala.io in README.md
Closes https://github.com/coala/projects/issues/142

README.md : Mention projects.coala.io

---

data/projects/editor_support.md

editor_support.md: Add details

---

data/faq.js
data/faq/is_mentor_necessary.md

The question is added in faq.js and
its answer is a '*.md' file in data/FAQ
Closes https://github.com/coala/projects/issues/181
them.
When asked for a …

FAQ: Add mentor necessity FAQ

---

data/projects/create_jenkins_plugin.md

Signed-off-by: Ce Gao <ce.gao@outlook.com>
them.
instead.
Please consider …

create_jenkins_plugin.md: Add goal and motivation

---

data/projects.js
data/projects/documentation_extraction.md

New Project: Documentation Extraction and Parsing

---

data/projects/editor_support.md

editor_support.md: Remove headings

---

data/projects/bear_updates.md

bear_updates.md: Improve description

---

data/projects.js

projects: Add mentor Mixih

---

data/projects/nested_languages.md

nested_languages.md: Improve description

---

data/projects/implement_aspects.md

implement_aspects.md: Add description

---

data/projects.js
data/projects/roberta_external_source.md

As talked over with @sims1253 and @sils, here's the project proposal for a coala gsoc-project in collaboration with the openroberta project at Fraunhofer IAIS. Fraunhofer is also willing to co-mentor.

Roberta gsoc colab project

---

resources/css/style.css

This will improve readability in large screens
Fixes https://github.com/coala/projects/issues/30
them. …

style.css: Add max width property to project details view

---

data/projects.js
data/projects/integrate-pyflakes-AST.md

@jayvdb Can you check this? Like you suggested I did not add the dead code fixing part.

Add integrate pyflakes enhanced AST into coala project

---

data/projects/generic_bears.md

Closes https://github.com/coala/projects/issues/206
them.
instead.
Please …

generic_bears.md: Change font of 'MILESTONES'

---

data/projects.js
data/projects/optimize_caching.md

Optimize Caching: Improve Description

---

data/projects/implement_metrics_for_coala.md

Implement Metrics for coala: Improve Description

---

data/faq.js
data/faq/project_participation.md

faq: Add project participation question

---

data/projects.js

projects.js: Change difficulty from hard to high

---

data/projects/create_jenkins_plugin.md

Jenkins Plugin: Minor changes

---

data/projects/implement_aspects.md

Hi,
Please review the pull request .
Fixes: https://github.com/coala/projects/issues/208
Thank You

fixed_typo

---

data/projects/generic_bears.md

Generic Bears: Add link to issues

---

data/projects/rstcheck_with_better_sphinx_support.md

This addresses #81 for the `rstcheck` project.

Further expand introduction of rstcheck project

---

partials/tabs/projects.html
resources/css/style.css

projects.html: Add high involvement flag

---

data/projects.js

Add crowded for website project

---

partials/tabs/projects.html
resources/css/style.css

projects.html: Add completed and in_progress status flag

---

data/faq/writing_a_great_proposal.md

Last line of writing_great_proposal.md showing up properly on the website with the link.
Closes https://github.com/coala/projects/issues/234
them. …

writing_a_great_proposal.md: Line not showing up on website

---

data/faq/application_template.md

changed from 'to you have to' to 'do you have to' in the sentence 'What parts of coala to you have to work with in order to complete this project? What else are you planning on using?'
Fixes https://github.com/coala/projects/issues/236
them.
pass on every …

data/faq/application_template.md: Corrected a typo

---

data/faq/thesis.md

Closes https://github.com/coala/projects/issues/249
them.
instead.
Please …

thesis.md: Fix missing link

---

data/projects.js
data/projects/enhance_coala_quickstart.md

Related to extracting useful information from
configuration files and improving user-interface.
them. …

New Project: Enhance coala-quickstart

---

data/projects/debug_profile.md

Correct typo in word "documentation"
Closes https://github.com/coala/projects/issues/253
them.
instead.
Please consider helping us by reviewing other peoples pull requests as well:
- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs …

debug_profile.md: Fix typo

---

data/projects/antlr_v4.md

This commit fixes typo in Integrate ANTLR project
description by changing `Succesful` to `Successful`.
Closes https://github.com/coala/projects/issues/263
them.
After you submit your pull request, **DO NOT click the 'Update Branch' …

antlr_v4.md: Fix Typo in Integrate ANTLR project description

---

data/projects.js

Mark crowded projects crowded

---

data/projects.js
data/projects/newcomer_metrics.md

Newcomer process metrics

---

data/projects/jetbrains-ide-plugin.md

Jetbrains Plugin: Minor changes

---

data/projects.js

projects.js: Mark projects as in_progress

---

data/projects/extend_linter_integration.md

extend_linter_integration.md: Update milestones

---

data/projects.js
data/projects/coala_web.md

coala_web.md: Update project description and milestones

---

data/projects.js
data/projects/implement_aspects.md

Relates to https://gitlab.com/coala/GSoC-2017/issues/139
- [x ] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [x ] I ran coala over my code locally. (*All commits have to pass
After you submit …

Implement aspect: Update project description

---

data/projects.js
data/projects/cobot_enhancement.md

projects: Add cobot enhancement project

---

data/projects/extend_linter_integration.md

extend_linter_integration: Fix render issues

---

data/projects/enhance_coala_quickstart.md

* Remove redundant milestone links
* Update the status of the project

enhance-quickstart: Update description

---

data/projects/vulture.md

This is a continuation of https://github.com/coala/projects/pull/287

Update proposal info for vulture

---

data/projects.js
partials/tabs/projects.html

Added Developers Involved Field for Projects In Progress

---

.coafile
data/projects.js
data/projects/use_coala.md
data/projects/use_coala_2.md
data/projects/use_coala_3.md

The markdown comes from the following three pages:
- https://github.com/coala/coala/wiki/Google-Code-In-Task-Use-coala
- https://github.com/coala/coala/wiki/Google-Code-In-Task-Use-coala-Advanced
- https://github.com/coala/coala/wiki/Google-Code-In-Task-Implement-coala
Related to https://github.com/coala/projects/issues/299

Add GCI task series "Use coala"

---

data/locale/id/faq.json
data/locale/id/faq/contact_mentor.md
data/locale/id/projects.json
data/locale/id/projects/roberta_external_source.md
index.html
partials/tabs/faq.html
partials/tabs/projects.html
resources/js/app.js

Now, we can add translation in:
``data/locale/<lang>/faq.json``
``data/locale/<lang>/faq/<filename.md>``
``data/locale/<lang>/projects.json``
``data/locale/<lang>/projects/<filename.md>``
At bottom left, you will see a select button to select language.
It will set variable ``lang`` to localStorage.
then, projects directive and faq directive will process it to translate content.

Add i18n functionality

---

data/locale/id/faq.json

Added translation to FAQ.
Closes https://github.com/coala/projects/issues/325
them. …

faq.json: Finish translation to bahasa

---

data/locale/ro/faq.json
resources/js/app.js

Closes https://github.com/coala/projects/issues/335

faq.json: Add translation to romanian

---

_projects/bear_updates.md
_projects/communication_bridge.md
_projects/debug_profile.md
_projects/nested_languages.md
_projects/optimize_caching.md

Tags marking projects as "High Involvement" have been removed.
Closes https://github.com/coala/projects/issues/291
them.
When asked for a rebase, …

projects.html: Remove High Involvement tags

---

_layouts/report.md
reports/hemang.md
resources/css/style.css
resources/js/app.js

reports: Add report layout

---

reports/nkprince007.md

reports: Add Naveen Kumar Sangi

---

reports/hemang.md

reports: Rename url

---

reports/alex.md

Closes https://github.com/coala/projects/issues/349

Add Alex's Status Report

---

reports/RJ722.md

reports: Add Rahul Jha

---

reports/example.md

reports: Add example report

---

reports/alex.md

Closes https://github.com/coala/projects/issues/355

Change Alex's bio

---

_layouts/report.md

report.md: Add title to commits table

---

reports/adhikasp.md

reports: Fix wrong mentor link

---

reports/meetmangukiya.md

reports: Add Meet Mangukiya's report

---

reports/RJ722.md

Updating the report to reflect upon the fact that https://github.com/coala/coala-bears/pull/2000 has been merged.
them.
When asked for a rebase, …

RJ722: Update report

---

reports/satwikkansal.md

reports: Add Satwik's GSoC report

---

reports/meetmangukiya.md

meetmangukiya.md: Add missing activity

---

reports/satwikkansal.md

Adds missing URLs in the markdown.
them.
instead.
Please consider helping …

Satwik's GSoC report: Fix missing links

---

.coafile
.travis.yml
_config.yml

Add YAMLLintBear for fixing issues with .yml files.
Closes https://github.com/coala/projects/issues/313
them. …

.coafile: Add YAMLLintBear

---

_projects/aspects.md
_projects/coala_cli.md
_projects/coala_web.md
_projects/cobot_enhancement.md
_projects/documentation_extraction.md
_projects/enhance_coala_quickstart.md
_projects/extend_linter_integration.md
_projects/gitmate_gitlab.md
_projects/implement_aspects.md
_projects/vulture.md

_projects: Change in_progress to completed for finished projects

---

index.html

Changes the position of language drop-down, placing it on the bottom-left of the screen.
Closes https://github.com/coala/projects/issues/363
them. …

Changed language Drop-Down position

---

_projects/improve_installation.md

Add Improve Installation of bears

---

_projects/add_repo_license.md

Replaced spaces with _ in the template used in STEP 3 URL used to create license task.
Fixes #383 
them. …

add_repo_license.md : Replaced spaces with _ in template

---

_projects/improve_installation.md

Improve installation of bears: Add link to cEPs

---

index.html

Fix language drop-down menu spacing issues.
Closes #363
them.
instead. …

Fixed language drop-down menu position.

---

_projects/assign_issues.md
_projects/assign_pull_requests.md

Rebased version of https://github.com/coala/projects/pull/170

Rebased: Automatically assign developers to new projects and issues

---

_projects/debug_profile.md
_projects/improve_diff_handling.md

Closes https://github.com/coala/projects/issues/280
them.
instead.
Please …

debug_profile.md: Fix spelling mistake 'desireable'

---

_faq/thesis.md

Fixed typo in thesis.md file,
`recommend` was misspelled as
`recoment`
Closes #411
them. …

thesis.md: Fix typo in file

---

resources/css/style.css

Adds the Pointer type cursor to Navbar Tabs so that user know that
they are clickable.
Closes https://github.com/coala/projects/issues/318
them.
When …

style.css: Cursor pointer added to navbar tabs

---

_projects/use_coala.md

Fixes typo of met to meet in
_projects/use_coala.md
Closes: https://github.com/coala/projects/issues/419
them. …

use_coala.md: Fix typo

---

_layouts/report.md

**Submitted for PR following request from GCI mentor.**
them.
instead. …

Reports mailto links clickable

---

_projects/gitmate_jira.md

Add GitMate Jira project

---

partials/tabs/projects.html
resources/js/app.js

Projects are sorted in the following order: pending, crowded, in progress and completed.
Fixes https://github.com/coala/projects/issues/437
Demonstration:
them.
After you submit your pull request, **DO NOT click the 'Update Branch' …

projects.html, app.js: Sort projects by status

---

_projects/gitmate_testing.md
resources/js/app.js

GSoC: Add GitMate testing project

---

README.md

Jekyll Troubleshoot link added in README

---

_projects/newcomer_metrics.md

This adds a prerequisite for newcomers to solve issues from coala/community repository as these issues are suitable for them.
Fixes https://github.com/coala/projects/issues/450
them.
After you submit your pull request, **DO NOT …

newcomer_metrics.md: Update requirements

---

_projects/improve_diff_handling.md

Sorry I don'y have the capacity to be a GSoC mentor this year.
Removing my name from the list.

Remove Mariatta from mentor's list.

---

_projects/nested_languages.md

Fixes #445 
them.
instead.
Please consider helping us by reviewing other …

Re-label Handling Nested Languages to Difficulty: High

---

_projects/assign_issues.md

This project has been implemented as part of GitMate by now.

assign_issues: Mark completed

---

_projects/use_coala.md
_projects/use_coala_2.md
_projects/use_coala_3.md

This commit changes all occurrences of 2016 to 2017 and the project
links with the new ones in `use_coala.md`, `use_coala_2.md` and
`use_coala_3.md`.
Closes https://github.com/coala/projects/issues/433
them.
After you submit your …

Update the CI1, CI2 , & CI3 tasks to refer to 2017

---

_projects/bear_updates.md

Fix typo in line 52, indetified --> identified
Closes https://github.com/coala/projects/issues/465
them. …

bear_updates.md: Fix typo

---

_faq/application_template.md

This fixes the typo and changes line 54
to --> do
Fixes https://github.com/coala/projects/issues/474
them. …

application_template.md: Fix typo

---

_projects/antlr_v4.md

antlr_v4.md: Add aptrishu as mentor

---

_projects/antlr_v4.md

antlr_v4.md: Add mentor corona10

---

partials/tabs/mentors.html

mentors.html: Update for GSoC 2018

---

_projects/improve_diff_handling.md

improve_diff_handling.md: Add mentor satwikkansal

---

resources/css/style.css

Fixes #375 
them.
instead.
Please consider helping us by reviewing other …

Fixes #375: Center project name in modal

---

_projects/nextgen_action_system.md

This file contains a new project's proposal for GSoC 2018.
them.
instead. …

nextgen_action_system.md: New project proposal

---

_projects/gitmate_jira.md

gitmate_jira.md: Mark status as in_progress

---

_faq/application_template.md

Fixes https://github.com/coala/projects/issues/441
them.
instead.
Please …

application_template.md: Updates the year

---

_faq/application_template.md

Since we need to ensure if the applicants use proper username,
we should add a new item for username checking url.
Closes https://github.com/coala/projects/issues/501
them.
After you submit your pull request, **DO NOT click the …

application_template.md: Add a new item for username checking url 

---

_projects/improve_diff_handling.md

* Add more details
* Add sample mockups
* Add deliverables
* Update Milestones (more tasks)
them. …

improve_diff_handling: Update description

---

resources/css/style.css

Fixes https://github.com/coala/projects/issues/417
them.
instead.
Please …

resources/css/styles: Clickable icon on hover

---

_projects/coala_language_server.md

Signed-off-by: Ce Gao <ce.gao@outlook.com>
them.
instead.
Please consider …

projects: Add coala Language Server

---

_projects/bear_updates.md

Closes https://github.com/coala/projects/issues/516
them.
instead.
Please …

bear_updates: Add crowded label

---

_faq/application_template.md

I deleted the first geographical boundary question
closes https://github.com/coala/projects/issues/508

application_template.md: Delete duplicate

---

_projects/antlr_v4.md
_projects/commit-content-checks.md
_projects/debug_profile.md
_projects/improve_installation.md

Closes https://github.com/coala/projects/issues/522
them.
instead.
Please …

Marked Some Project Ideas as crowded

---

partials/tabs/projects.html

Closes https://github.com/coala/projects/issues/521
them.
instead.
Please …

projects.html: Add more project ideas link

---

_projects/add_repo_license.md
_projects/use_coala.md
_projects/use_coala_2.md
_projects/use_coala_3.md

Closes https://github.com/coala/projects/issues/479
them.
instead.
Please …

Add 'status: completed' to all GCI projects

---

_faq/application_template.md

Closes https://github.com/coala/projects/issues/469

application_template: Add element for upstream commits

---

_projects/gitmate_plugins.md

Ref: https://github.com/coala/projects/issues/488
them.
instead.
Please …

GitMate plugins project idea

---

_projects/create_jenkins_plugin.md
_projects/roberta_external_source.md
partials/tabs/projects.html

This adds a disabled label to the OpenRoberta and Jenkins projects. Each project contains a description with a link to their respective GSOC pages.
Closes https://github.com/coala/projects/issues/447 and https://github.com/coala/projects/issues/448
them.
pass …

Mark projects as disabled

---

_projects/coala_language_server.md
_projects/newcomer_metrics.md

Closes https://github.com/coala/projects/issues/530
them.
instead.
Please …

Mark two project ideas as crowded

---

_projects/automate_dependacy_repology.md

Closes https://github.com/coala/projects/issues/497
them.
instead.
Please …

_projects: Add automate_dependacy_repology.md

---

_projects/corobo_enhancement.md

Closes https://github.com/coala/projects/issues/498
them.
instead.
Please …

corobo_enhancement: Add corobo enhancement project

---

_projects/gitmate_plugins.md

Add about auto-assign issue based on commit
mention task.
them.
instead. …

gitmate_plugins.md: Add auto-assign plugin

---

_faq/high_involvement_status.md

closes https://github.com/coala/projects/issues/525
them.
instead.
Please …

high_involvement_status.md: Add FAQ about status high involvement

---

_projects/newcomer_metrics.md

newcomer_metrics.md: Add prnvdixit to mentor's list

---

_faq/mentor_obligations.md

Add mentor roles
Closes https://github.com/coala/projects/issues/503

mentor_obligations.md: Update faq

---

_projects/coala_language_server.md

Add mentor gatesn
them.
instead.
Please consider helping us by reviewing …

_projects/coala_language_server.md: Add mentor

---

_projects/quickstart_green_mode.md

Closes: https://github.com/coala/projects/issues/506

quickstart_green_mode.md: Add Quickstart Green Mode Project

---

README.md
_config.yml
_projects/example.md

This moves example project written on README.md to _projects under the name example.md and excluded from appearing in the project list.
Closes https://github.com/coala/projects/issues/484
them.
After you submit your pull request, …

README.md: Move example project to _projects/example.md

---

.coafile
.travis.yml

This closes Issue https://github.com/coala/projects/issues/463
them. …

Added GitCommitBear

---

_projects/example.md

Closes https://github.com/coala/projects/issues/490

example.md: Revise sample project

---

_config.yml

This moves example project to _projects folder as example.md
and skip it from appearing in the project list
Closes https://github.com/coala/projects/issues/484
them.
After you submit your pull request, **DO NOT click the 'Update …

_config.yml: Exclude example project 

---

_projects/meta_review.md

Related to https://github.com/coala/projects/issues/480
them.
instead. …

meta_review.md: Add meta review project

---

.coafile
_projects/coala_cli.md
_projects/coala_web.md
_projects/cobot_enhancement.md
_projects/documentation_extraction.md
_projects/enhance_coala_quickstart.md
_projects/gitmate_gitlab.md
_projects/gitmate_jira.md
_projects/implement_aspects.md
reports/RJ722.md
reports/adhikasp.md
reports/alex.md
reports/hemang.md
reports/meetmangukiya.md
reports/nkprince007.md
reports/satwikkansal.md

Closed https://github.com/coala/projects/issues/557
them.
instead.
Please …

Updating links of GSoC 17

---

_projects/vulture.md

Closes https://github.com/coala/projects/issues/580
them.
instead.
Please …

vulture.md: Fix broken link

---

_projects/coala_language_server.md

This updates the milestones and details of the coala language server project.
Closes https://github.com/coala/projects/issues/569
them.
When asked for …

coala_language_server.md: Update project details

---

_projects/go_bears_on_bsd.md

go_bears_on_bsd.md: Add Go on BSD project

---

_projects/git_task_list.md

git_task_list.md: Update repository's URL

---

_projects/automate_dependacy_repology.md

Also removes mentor xferra, who was moved to
the newer BSD specific repology project.
them. …

automate_dependacy_repology.md: Add mentor underyx

---

_projects/optimize_caching.md

optimize_caching.md: Change project description

---

_projects/automate_vulture_whitelist.md

Add automatic whitelist generator for vulture

---

_projects/git_task_list.md

Closes https://github.com/coala/projects/issues/594
them.
instead.
Please …

git_task_list.md: Fix vague link

---

_layouts/report.md

Closes https://github.com/coala/projects/issues/608
Example usage : https://github.com/virresh/projects/tree/sample
them.
When asked for a rebase, …

report.md: Make GSoC year dynamic

---

_projects/commit_based_perftest.md

This fixes the typo and changes the variable name
for project from intiatives --> initiatives.
Fixes https://github.com/coala/projects/issues/620
them.
After you submit your pull request, **DO NOT click the 'Update Branch' …

commit_based_perftest.md: Fix docstring typo

---

reports/li-boxuan.md

https://deploy-preview-618--coala-projects.netlify.com/gsoc/2018/statusreport/li-boxuan

reports: Add li-boxuan's GSoC report

---

reports/pareksha.md

https://deploy-preview-610--coala-projects.netlify.com/gsoc/2018/statusreport/pareksha

reports: Add pareksha's GSoC report

---

_reports/RaiVaibhav.md

GSoC-2018 report
https://deploy-preview-611--coala-projects.netlify.com/gsoc/2018/statusreport/vaibhavrai

reports: Add Vaibhav Rai GSoC report

---

_reports/virresh.md

https://deploy-preview-617--coala-projects.netlify.com/gsoc/2018/statusreport/virresh

report: Add virresh's GSoC report

---

_reports/palash25.md

reports: Add palash25.md

---

_reports/ksdme.md

https://deploy-preview-632--coala-projects.netlify.com/gsoc/2018/statusreport/ksdme

reports: Add ksdme's GSoC report

---

_reports/RJ722.md

Add Report for RJ722.
~~https://deploy-preview-622--coala-projects.netlify.com/GSoC/2018/StatusReport/RahulJha~~
https://deploy-preview-622--coala-projects.netlify.com/gsoc/2018/statusreport/rj722

reports: Add report for RJ722 2018

---

_reports/RJ722.md

* Add permalink
* Add new commit

_reports/RJ722.md: Update report for RJ722

---

_reports/ishanSrt.md

Add ishanSrt's report

---

_reports/ishanSrt.md

Update ishanSrt's report

---

reports.html

Closes https://github.com/coala/projects/issues/359
them.
instead.
Please …

reports.html: Create report listing

---

_projects/antlr_v4.md
_projects/automate_dependency_repology.md
_projects/automate_vulture_whitelist.md
_projects/bear_updates.md
_projects/coala_language_server.md
_projects/commit-content-checks.md
_projects/convert_bear_to_aspects.md
_projects/corobo_enhancement.md
_projects/debug_profile.md
_projects/editor_support.md
_projects/gitmate_jira.md
_projects/gitmate_plugins.md
_projects/go_bears_on_bsd.md
_projects/improve_installation.md
_projects/integrate-pyflakes-AST.md
_projects/meta_review.md
_projects/nested_languages.md
_projects/newcomer_metrics.md
_projects/optimize_caching.md
_projects/quickstart_green_mode.md

This updates the status of GSoC 2018 projects in [projects.coala.io](https://projects.coala.io/#/projects)
Closes https://github.com/coala/projects/issues/636
them.
After you submit your pull request, **DO NOT click the 'Update …

_projects: Update status of GSoC 2018 projects

---

.gitignore

Sync moban templates which was causing the build failure.
them.
instead. …

moban: Sync moban templates

---

_projects/add-repo-license.md

- Replace broken link with the github link
Closes #660
them.
instead. …

add-repo-license.md: Replace broken link

---

.editorconfig

Closes https://github.com/coala/projects/issues/388
them.
instead.
Please …

.editorconfig: Add new file

---

.gitignore

.gitignore: Sync moban

---

_faq/coala-will-apply-for-gsoc-2018.md
_faq/coala-will-apply-for-gsoc.md

Closes https://github.com/coala/projects/issues/672
- [*] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [*] I ran coala over my code locally. (*All commits have to pass
After you submit your pull …

coala-will-apply-for-gsoc-2018.md: Remove references to specific years

---

tools/authorPatchCollector.py

Closes https://github.com/coala/meta/issues/124
them.
instead.
Please …

authorPatchCollector.py: Add GSOC patch collector

---

reports.html

Replace hard coded year headings with auto-generated year headings based on reports in `_reports`.
Regards issue #670

reports.html: Create dynamic report listing by year

---

data/locale/id/faq/coala-will-apply-for-gsoc.md

Related to #324
them.
instead.
Please consider helping us by reviewing …

FAQ: Finish Indonesian translation

---

_projects/standardised-file-format.md

This adds new projectproposal to current projects list
Closes https://github.com/coala/projects/issues/705
them. …

Add Support TOML Project to projects list

---

_reports/akshatkarani.md

Add akshatkarani report

---

_faq/cep-and-its-importance.md

This faq helps contributor in understanding about cEP and its
importance.
Closes #684

_faq: Add details about cEPs to faq

---

_config.yml
index.html
resources/css/style.css

This commit updates the current footer design,
similar to that of [coala](coala.io) website.
CLoses #184

index.html: Update footer design

---

_reports/Naveenaidu.md

Add Naveenaidu report

---

_reports/PrajwalM.md

Add Prajwal M report

---

_reports/bkhanale.md

Add bkhanale report

---

_reports/RohanVB.md

Add RohanVB report

---

_reports/chay2199.md

Add chay2199 report

---

.coafile
_reports/AmolGrover.md

Work Product Submission Report
for GSoC 2019
them.
instead.
Please …

Add report for Amol Grover

---

_reports/A-Hilaly.md

Add A-Hilaly report

---

_reports/Utkarsh1308.md

Add Utkarsh Sharma's GSoC report

---

.coafile
.travis.yml

An attempt to fix build errors.

.travis.yml: Fix build errors

---

.coafile
.travis.yml
_layouts/report.md
resources/css/404.css
resources/css/style.css

The commit adds a new section in .coafile
which will be responsible for linting css files
and, check if there are any error or not.

Use CSSLintBear

---

_projects/editor-support.md
_projects/enhance-and-improve-coala-community-and-projects-website.md
_projects/generic-bears.md
_projects/git-bug.md
_projects/improve-diff-handling.md
_projects/jetbrains-ide-plugin.md
_projects/nested-languages.md
_projects/nextgen-action-system.md
_projects/result-reporter-tool.md
_projects/standardised-file-format.md

The commit marks the projects status as completed
for all Google Summer of Code'19 projects.
Closes https://github.com/coala/projects/issues/756

_projects: Update GSoC'19 projects status

---

_reports/Naveenaidu.md

Naveenaidu report: Add missing fields

---

_reports/RohanVB.md

RohanVB report: Add missing fields

---

_faq/writing-a-great-proposal.md

Changes the old broken link with the new link
google.github.io/gsocguides/student
closes https://github.com/coala/projects/issues/642
them.
When asked …

writing_a_great_proposol.md: update gsoc link

---

_projects/generic-bears.md
_projects/nextgen-action-system.md

The mentor list for some of the projects was
outdated. This updates the list of those mentors.
them. …

Add new mentors for GSoC projects

---

.coafile
.travis.yml
_projects/gitmate-coala.md
_projects/improve-corobo.md
_projects/python-support.md

Add GSoC'21 Projects

---

.coafile
_projects/git-bug2.md

@abhishalya asked to to create that project page for git-bug, which will participate to the Summer of Code, thanks to Coala!
Hopefully I got that right.

_projects: add git-bug

---

partials/tabs/projects.html

This adds Difficulty-level and Tags rows under mentors row in project section.
Closes #786
them. …

projects.html: Add difficulty row

---

partials/tabs/projects.html

This will remove trailing whitespaces and fix its inconsistency.
[Here](https://travis-ci.com/github/pra17dod/projects/builds/225132317) is the link to Travis build.
Fixes https://github.com/coala/projects/issues/795
them.
After …

projects.html: Fix inconsistent whitespaces

---

_reports/pilgrim2308.md

This is the report for GSoC 2021 project
GitMate for coala by pilgrim2308.

Add pilgrim2308's report
